name: smooth_study
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  cloud_firestore: ^4.8.1
  internet_connection_checker_plus: ^1.0.1
  connectivity_plus: ^4.0.1
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.4.0
  internet_file: ^1.2.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/svg/
    - assets/lvl.png


